/* eslint-disable @typescript-eslint/no-deprecated -- Keep exporting the deprecated API key compatibility surface. */
// OAuth Extension Schemas (v1)
export {
  OAuthConfigSchema,
  OAuthProviderSchema,
  OAuthAuthScopeSchema,
  OAuthProviderSupportedLocaleSchema,
  OAuthProviderLocalizedTextSchema,
  OAuthProviderI18nMapSchema,
  CredentialValidationResultSchema,
  CredentialValidationInputSchema,
  ParameterCaseSchema,
  TokenRequestContentTypeSchema,
  AuthorizationOpenModeSchema,
  OAuthTokenRequestMappingSchema,
  OAuthTokenResponseMappingSchema,
  type OAuthConfig,
  type OAuthProvider,
  type OAuthAuthScope,
  type OAuthProviderSupportedLocale,
  type OAuthProviderLocalizedText,
  type OAuthProviderI18nMap,
  type CredentialValidationResult,
  type CredentialValidationInput,
  type ParameterCase,
  type TokenRequestContentType,
  type AuthorizationOpenMode,
  type OAuthTokenRequestMapping,
  type OAuthTokenResponseMapping,
} from "./oauth.js";

// API Key Extension Schemas (v1)
export {
  ApiKeyFieldSchema,
  ApiKeyAuthScope,
  GetAuthConfigOutputSchema,
  ValidateCredentialsOutputSchema,
  type ApiKeyField,
  type GetAuthConfigOutput,
  type ValidateCredentialsOutput,
} from "./apikey.js";

// Config Extension Schemas (v1)
export {
  ConfigScopeSchema,
  ConfigStorageClassSchema,
  ConfigConditionOperatorSchema,
  ConfigConditionSchema,
  LocalizedConfigTextSchema,
  ConfigSupportedLocaleSchema,
  ConfigI18nMapSchema,
  ConfigChoiceSchema,
  ConfigInlineLinkSchema,
  ConfigNoticeToneSchema,
  ConfigNoticePlacementSchema,
  ConfigValidationNoticeSchema,
  ConfigHooksSchema,
  ConfigOAuthAdditionalParamSchema,
  ConfigOAuthSchema,
  ConfigChoicesSourceSchema,
  ConfigDraftResolutionParamsSchema,
  ConfigResolvedValueTargetSchema,
  ConfigFieldSchema,
  ConfigBlockSchema,
  GetConfigSchemaOutputSchema,
  ConfigValidationErrorSchema,
  ValidateStoredConfigOutputSchema,
  ConfigDraftResolutionOutputSchema,
  type ConfigScope,
  type ConfigStorageClass,
  type ConfigMediaOptions,
  type ConfigConditionOperator,
  type ConfigCondition,
  type LocalizedConfigText,
  type ConfigSupportedLocale,
  type ConfigI18nMap,
  type ConfigChoice,
  type ConfigInlineLink,
  type ConfigNoticeTone,
  type ConfigNoticePlacement,
  type ConfigValidationNotice,
  type ConfigHooks,
  type ConfigOAuthAdditionalParam,
  type ConfigOAuth,
  type ConfigChoicesSource,
  type ConfigOverview,
  type ConfigDefaultSelector,
  type ConfigSettings,
  type ConfigDraftResolutionParams,
  type ConfigResolvedValueTarget,
  type ConfigField,
  type ConfigActionBlock,
  type ConfigBlock,
  type GetConfigSchemaOutput,
  type ConfigValidationError,
  type ValidateStoredConfigOutput,
  type ConfigDraftResolutionOutput,
} from "./config.js";

// Calendar Extension Schemas (v1)
export {
  CalendarSchema,
  EventTypeSchema,
  TimeSlotSchema,
  AttendeeSchema,
  BookingStatus,
  BookingSchema,
  type Calendar,
  type EventType,
  type TimeSlot,
  type Attendee,
  type Booking,
} from "./calendar.js";

// Command Extension Schemas (v1)
export {
  CommandScopeSchema,
  CommandAlfModeSchema,
  CommandParamTypeSchema,
  CommandNameI18nSchema,
  CommandNameDescI18nSchema,
  CommandParamDefI18nSchema,
  CommandChoiceSchema,
  CommandParamDefinitionSchema,
  CommandConfigSchema,
  GetCommandsOutputSchema,
  CommandResultSchema,
  type CommandScope,
  type CommandAlfMode,
  type CommandParamType,
  type CommandNameI18n,
  type CommandNameDescI18n,
  type CommandParamDefI18n,
  type CommandChoice,
  type CommandParamDefinition,
  type CommandConfig,
  type GetCommandsOutput,
  type CommandResult,
} from "./command.js";

// Widget Extension Schemas (v1)
export {
  WidgetScope,
  WidgetType,
  NameDescI18nSchema,
  WidgetConfigSchema,
  GetWidgetsOutputSchema,
  WidgetActionResultSchema,
  type NameDescI18n,
  type WidgetConfig,
  type GetWidgetsOutput,
  type WidgetActionResult,
} from "./widget.js";

// Custom Tab Extension Schemas (v1)
export {
  CustomTabNameI18nSchema,
  CustomTabConfigSchema,
  GetCustomTabsOutputSchema,
  CustomTabActionResultSchema,
  type CustomTabNameI18n,
  type CustomTabConfig,
  type GetCustomTabsOutput,
  type CustomTabActionResult,
} from "./customtab.js";

// Hook Extension Schemas (v1)
export {
  HookTypeSchema,
  WebhookConfigSchema,
  HookConfigSchema,
  GetHooksOutputSchema,
  type HookType,
  type WebhookConfig,
  type HookConfig,
  type GetHooksOutput,
} from "./hook.js";

// Mail Relay Extension Schemas (v1)
export {
  MailRelayHeaderSchema,
  MailRelayCommonHeadersSchema,
  MailRelayMailSchema,
  MailRelayReceiptSchema,
  MailRelayInboundInputSchema,
  MailRelayInboundStatusSchema,
  MailRelayInboundOutputSchema,
  type MailRelayHeader,
  type MailRelayCommonHeaders,
  type MailRelayMail,
  type MailRelayReceipt,
  type MailRelayInboundInput,
  type MailRelayInboundStatus,
  type MailRelayInboundOutput,
} from "./mail-relay.js";

// Polling Extension Schemas (v1)
export {
  PollingPollerSchema,
  GetPollersOutputSchema,
  GetPollingTargetChannelsInputSchema,
  GetPollingTargetChannelsOutputSchema,
  type PollingPoller,
  type GetPollersOutput,
  type GetPollingTargetChannelsInput,
  type GetPollingTargetChannelsOutput,
} from "./polling.js";

// Store Extension Schemas (v1)
export {
  StoreProfileImageSchema,
  StoreProfileIntroSchema,
  StoreFaqSchema,
  StoreProfileLocalizedContentSchema,
  StoreProfileMetadataSchema,
  StoreProfileI18nSchema,
  StoreProfileSchema,
  GetStoreProfileInputSchema,
  GetStoreProfileOutputSchema,
  defineStoreProfile,
  defineStoreProfileOutput,
  createStoreExtension,
  type StoreProfileImage,
  type StoreProfileIntro,
  type StoreFaq,
  type StoreProfileLocalizedContent,
  type StoreProfileMetadata,
  type StoreProfileI18n,
  type StoreProfile,
  type GetStoreProfileInput,
  type GetStoreProfileOutput,
  type StoreProfileProvider,
} from "./store.js";

// DataSource Extension Schemas (v1)
export {
  DataSourceDialectSchema,
  DataSourceTableTypeSchema,
  DataSourceManagerAccessSchema,
  DataSourceCatalogSchema,
  DataSourceTableSchema,
  DataSourceColumnSchema,
  DataSourceTableDefinitionSchema,
  DataSourceTableListingSchema,
  ListCatalogsInputSchema,
  ListCatalogsOutputSchema,
  ListTablesInputSchema,
  ListTablesOutputSchema,
  DescribeTableInputSchema,
  DescribeTableOutputSchema,
  DataSourceSamplePolicy,
  validateDataSourceSample,
  createDataSourceDedupKey,
  createDataSourceIngestionEventRow,
  normalizeDataSourceTimestamp,
  createDataSourceExtension,
  createStaticDataSourceExtension,
  type DataSourceDialect,
  type DataSourceTableType,
  type DataSourceManagerAccess,
  type DataSourceCatalog,
  type DataSourceTable,
  type DataSourceColumn,
  type DataSourceTableDefinition,
  type DataSourceTableListing,
  type SearchedTable,
  type ListCatalogsInput,
  type ListCatalogsOutput,
  type ListTablesInput,
  type ListTablesOutput,
  type DescribeTableInput,
  type DescribeTableOutput,
  type CreateDataSourceIngestionEventRowInput,
  type DataSourceIngestionEventRow,
  type DataSourceMetadataProvider,
  type StaticDataSourceMetadata,
} from "./datasource.js";

// ALF Task Extension Schemas (v1)
export {
  MemoryDefinitionSchema,
  WorkflowNodeSchema,
  PredefinedTaskSchema,
  GetAlfTasksInputSchema,
  GetAlfTasksResponseSchema,
  createAlfTaskExtensionV1,
  type MemoryDefinition,
  type WorkflowNode,
  type PredefinedTask,
  type GetAlfTasksInput,
  type GetAlfTasksResponse,
  type AlfTaskExtensionProvider,
} from "./alftask.js";

// Notebook Extension Schemas (v1)
export {
  NotebookCellTypeSchema,
  NotebookInitialVisibilitySchema,
  NotebookCellSchema,
  NotebookLayoutColumnSchema,
  NotebookLayoutRowSchema,
  NotebookTabSchema,
  NotebookPayloadSchema,
  AppNotebookSchema,
  GetNotebooksInputSchema,
  GetNotebooksResponseSchema,
  createNotebookExtensionV1,
  type NotebookCellType,
  type NotebookInitialVisibility,
  type NotebookCell,
  type NotebookLayoutColumn,
  type NotebookLayoutRow,
  type NotebookTab,
  type NotebookPayload,
  type AppNotebook,
  type GetNotebooksInput,
  type GetNotebooksResponse,
  type NotebookExtensionProvider,
} from "./notebook.js";

// Order Extension Schemas (v1)
export {
  AddressSchema,
  BuyerSchema,
  BankAccountSchema,
  DefectInfoSchema,
  ClaimReasonSchema,
  ClaimabilitySchema,
  ClaimSchema,
  OrderItemSchema,
  OrderClaimItemSchema,
  OrderExchangeItemSchema,
  PaymentSchema,
  FulfillmentSchema,
  OrderSchema,
  FieldConfigSchema,
  OperationOptionsSchema,
  AppCapabilitiesSchema,
  type Address,
  type Buyer,
  type BankAccount,
  type DefectInfo,
  type ClaimReason,
  type Claimability,
  type Claim,
  type OrderItem,
  type OrderClaimItem,
  type OrderExchangeItem,
  type Payment,
  type Fulfillment,
  type Order,
  type FieldConfig,
  type OperationOptions,
  type AppCapabilities,
} from "./order.js";

// WMS Extension Schemas (v1)
export {
  WmsShippingInfoSchema,
  WmsDeliverySchema,
  WmsOrderItemSchema,
  WmsOrderSchema,
  GetWmsOrdersInputSchema,
  GetWmsOrdersOutputSchema,
  GetWmsOrderInputSchema,
  GetWmsOrderOutputSchema,
  GetWmsShopIdInputSchema,
  GetWmsShopIdOutputSchema,
  GetWmsSupportedCommercesInputSchema,
  GetWmsSupportedCommercesOutputSchema,
  CancelWmsOrderInputSchema,
  ReturnWmsOrderInputSchema,
  ExchangeWmsOrderInputSchema,
  ChangeWmsShippingAddressInputSchema,
  RestoreWmsOrderInputSchema,
  WmsSuccessOutputSchema,
  type WmsShippingInfo,
  type WmsDelivery,
  type WmsOrderItem,
  type WmsOrder,
  type GetWmsOrdersInput,
  type GetWmsOrdersOutput,
  type GetWmsOrderInput,
  type GetWmsOrderOutput,
  type GetWmsShopIdInput,
  type GetWmsShopIdOutput,
  type GetWmsSupportedCommercesInput,
  type GetWmsSupportedCommercesOutput,
  type CancelWmsOrderInput,
  type ReturnWmsOrderInput,
  type ExchangeWmsOrderInput,
  type ChangeWmsShippingAddressInput,
  type RestoreWmsOrderInput,
  type WmsSuccessOutput,
  // order group (v2)
  WmsDeliveryV2Schema,
  WmsOrderItemV2Schema,
  WmsOrderV2Schema,
  WmsIdentifierSchema,
  WmsOrderGetOrdersInputSchema,
  WmsOrderGetOrdersOutputSchema,
  WmsOrderActionInputSchema,
  WmsOrderActionOutputSchema,
  WmsOrderChangeShippingAddressInputSchema,
  WmsGetAppConfigsInputSchema,
  WmsGetAppConfigsOutputSchema,
  WmsOperationOptionsSchema,
  WmsAppCapabilitiesSchema,
  type WmsDeliveryV2,
  type WmsOrderItemV2,
  type WmsOrderV2,
  type WmsIdentifier,
  type WmsOrderGetOrdersInput,
  type WmsOrderGetOrdersOutput,
  type WmsOrderActionInput,
  type WmsOrderActionOutput,
  type WmsOrderChangeShippingAddressInput,
  type WmsGetAppConfigsInput,
  type WmsGetAppConfigsOutput,
  type WmsOperationOptions,
  type WmsAppCapabilities,
} from "./wms.js";

// Commerce Extension Schemas (v1)
export {
  CommerceOrderItemSchema,
  CommerceOrderSchema,
  CommerceIdentifierSchema,
  CommerceGetOrdersInputSchema,
  CommerceGetOrdersOutputSchema,
  CommerceAppCapabilitiesSchema,
  CommerceGetAppConfigsOutputSchema,
  CommerceResultSchema,
  CommerceCancelOrderInputSchema,
  CommerceReturnOrderInputSchema,
  CommerceReturnAcceptOrderInputSchema,
  CommerceExchangeOrderInputSchema,
  CommerceGetExchangeableItemsInputSchema,
  CommerceGetExchangeableItemsOutputSchema,
  CommerceChangeShippingAddressInputSchema,
  type CommerceOrderItem,
  type CommerceOrder,
  type CommerceIdentifier,
  type CommerceGetOrdersInput,
  type CommerceGetOrdersOutput,
  type CommerceAppCapabilities,
  type CommerceGetAppConfigsOutput,
  type CommerceActionResult,
  type CommerceCancelOrderInput,
  type CommerceReturnOrderInput,
  type CommerceReturnAcceptOrderInput,
  type CommerceExchangeOrderInput,
  type CommerceGetExchangeableItemsInput,
  type CommerceGetExchangeableItemsOutput,
  type CommerceChangeShippingAddressInput,
} from "./commerce.js";

// Messaging Extension Schemas (v1)
export {
  MessagingAlfMessageTypeSchema,
  MessagingMeetModeSchema,
  MessagingMessageMeetStateSchema,
  MessagingMessageStateSchema,
  MessagingMessageColorVariantSchema,
  MessagingMessageOptionSchema,
  MessagingMessageAlertLevelSchema,
  MessagingWritingTypeSchema,
  MessagingUserChatStateSchema,
  MessagingUserChatGoalStateSchema,
  MessagingUserChatSubtextTypeSchema,
  MessagingMissedReasonSchema,
  MessagingUserTypeSchema,
  MessagingWritingTypeAvailabilityStateSchema,
  MessagingPrebuiltEntityTypeSchema,
  MessagingAlfSchema,
  MessagingMeetSchema,
  MessagingMessageFileSchema,
  MessagingPartialMessageFileSchema,
  MessagingMessageThreadSchema,
  MessagingMessageButtonSchema,
  MessagingCustomPayloadSchema,
  MessagingMessageSchema,
  MessagingPartialMessageSchema,
  MessagingPrebuiltMessageSchema,
  MessagingPrebuiltPartialMessageSchema,
  MessagingUserChatSchema,
  MessagingUserSchema,
  MessagingWamResultSchema,
  MessagingUnavailableReasonSchema,
  MessagingWritingTypeStateSchema,
  MessagingWritingTypeMapSchema,
  MessagingMediumProfileSchema,
  OnMediumMessageCreatedInputSchema,
  OnMediumMessageCreatedOutputSchema,
  InboxOnMediumUserChatClosedInputSchema,
  InboxOnMediumUserChatClosedOutputSchema,
  InboxGetWritingTypesInputSchema,
  InboxGetWritingTypesOutputSchema,
  InboxGetCustomEditorWamInputSchema,
  InboxGetCustomEditorWamOutputSchema,
  InboxGetMediumTopicSelectorWamInputSchema,
  InboxGetMediumTopicSelectorWamOutputSchema,
  InboxGetMediumMessageErrorReasonInputSchema,
  InboxGetMediumMessageErrorReasonOutputSchema,
  PrebuiltGetWritingTypesInputSchema,
  PrebuiltGetWritingTypesOutputSchema,
  PrebuiltValidateEntityInputSchema,
  PrebuiltValidateEntityOutputSchema,
  PrebuiltGetCustomEditorWamInputSchema,
  PrebuiltGetCustomEditorWamOutputSchema,
  PrebuiltGetMediumTopicBuilderSelectorWamInputSchema,
  PrebuiltGetMediumTopicBuilderSelectorWamOutputSchema,
  PrebuiltBuildMediumTopicsInputSchema,
  PrebuiltBuildMediumTopicsOutputSchema,
  PrebuiltGetDefaultOptionsInputSchema,
  PrebuiltGetDefaultOptionsOutputSchema,
  type MessagingAlfMessageType,
  type MessagingMeetMode,
  type MessagingMessageMeetState,
  type MessagingMessageState,
  type MessagingMessageColorVariant,
  type MessagingMessageOption,
  type MessagingMessageAlertLevel,
  type MessagingWritingType,
  type MessagingUserChatState,
  type MessagingUserChatGoalState,
  type MessagingUserChatSubtextType,
  type MessagingMissedReason,
  type MessagingUserType,
  type MessagingWritingTypeAvailabilityState,
  type MessagingPrebuiltEntityType,
  type MessagingAlf,
  type MessagingMeet,
  type MessagingMessageFile,
  type MessagingPartialMessageFile,
  type MessagingMessageThread,
  type MessagingMessageButton,
  type MessagingCustomPayload,
  type MessagingMessage,
  type MessagingPartialMessage,
  type MessagingPrebuiltMessage,
  type MessagingPrebuiltPartialMessage,
  type MessagingUserChat,
  type MessagingUser,
  type MessagingWamResult,
  type MessagingUnavailableReason,
  type MessagingWritingTypeState,
  type MessagingWritingTypeMap,
  type MessagingMediumProfile,
  type OnMediumMessageCreatedInput,
  type OnMediumMessageCreatedOutput,
  type InboxOnMediumUserChatClosedInput,
  type InboxOnMediumUserChatClosedOutput,
  type InboxGetWritingTypesInput,
  type InboxGetWritingTypesOutput,
  type InboxGetCustomEditorWamInput,
  type InboxGetCustomEditorWamOutput,
  type InboxGetMediumTopicSelectorWamInput,
  type InboxGetMediumTopicSelectorWamOutput,
  type InboxGetMediumMessageErrorReasonInput,
  type InboxGetMediumMessageErrorReasonOutput,
  type PrebuiltGetWritingTypesInput,
  type PrebuiltGetWritingTypesOutput,
  type PrebuiltValidateEntityInput,
  type PrebuiltValidateEntityOutput,
  type PrebuiltGetCustomEditorWamInput,
  type PrebuiltGetCustomEditorWamOutput,
  type PrebuiltGetMediumTopicBuilderSelectorWamInput,
  type PrebuiltGetMediumTopicBuilderSelectorWamOutput,
  type PrebuiltBuildMediumTopicsInput,
  type PrebuiltBuildMediumTopicsOutput,
  type PrebuiltGetDefaultOptionsInput,
  type PrebuiltGetDefaultOptionsOutput,
} from "./messaging.js";

// Canonical extension function schema registry
export {
  extensionFunctionSchemaDefinitions,
  getExtensionFunctionSchemas,
} from "./function-schemas.js";

// Extension Interfaces (for implementing extensions)
export * from "./interfaces/index.js";
